apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: sampleapp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: sampleapp-api-ingress
spec:
  rules:
  - host: sampleapp.dominiodeexemplo.com
    http:
      paths:
      pathType: ImplementationSpecific
      - defaultBackend:
          service.name: sampleapp-api-svc
          service.port.number: 80
        path: /(.*)
