apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: sampleapp
  name: sampleapp-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: sampleapp.vidadeumsysadmin.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sampleapp-api-svc
            port:
              number: 80
